apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-go
  namespace: simple-otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-go
  template:
    metadata:
      labels:
        app: todo-api-go
    spec:
      containers:
        - name: todo-api-go
          image: todo-api-go:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          envFrom:
            - configMapRef:
                name: todo-api-go-env
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 10