apiVersion: v1
kind: Service
metadata:
  name: todo-api-go
  namespace: simple-otel
spec:
  selector:
    app: todo-api-go
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900