apiVersion: v1
kind: Service
metadata:
  name: todo-api-nodejs
  namespace: simple-otel
spec:
  selector:
    app: todo-api-nodejs
  type: NodePort
  ports:
    - name: http
      port: 9100
      targetPort: 9100
      nodePort: 30910